# Generated by Django 3.1.3 on 2021-01-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdctManage', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
