# Generated by Django 3.1.3 on 2021-01-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdctManage', '0003_lecture_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
