# Generated by Django 3.1.3 on 2021-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdctManage', '0006_feedback_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
