# Generated by Django 3.1.3 on 2021-01-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdctManage', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='voter',
            field=models.ManyToManyField(related_name='voter_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='voter',
            field=models.ManyToManyField(related_name='voter_lecture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_lecture', to=settings.AUTH_USER_MODEL),
        ),
    ]
