# Generated by Django 3.1.3 on 2021-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdctManage', '0009_auto_20210129_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
